server:
  port: 8081
  servlet:
    context-path: /alahub

spring:
  application:
    name: education
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:test}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:010203}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
